### ISSUE TITLE
I have an error when training with my own dataset

### ISSUE THREAD

**Issue by SungjinChoi1128** [NVIDIA/pix2pixHD#100]
I am trying to train with my own dataset with the size of 2048*1024
and i have label image and number of label class is set 13.
I got this error and anyone can help me find out why this error occurs
My command and error message are below

python train.py --name label2city_1024p_12G --batchSize 8 --no_instance --label_nc 13 --resize_or_crop none --save_epoch_freq 200

create web directory ./checkpoints/label2city_512p/web...
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/pix2pixHD/models/pix2pixHD_model.py", line 165, in forward
    fake_image = self.netG.forward(input_concat)
  File "/home/ubuntu/pix2pixHD/models/networks.py", line 213, in forward
    return self.model(input)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/aten/src/THC/THCCachingAllocator.cpp:470)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f89b602f021 in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f89b602e8ea in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13dbd92 (0x7f893ec2cd92 in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #3: at::TensorImpl::release_resources() + 0x50 (0x7f893408d440 in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #4: <unknown function> + 0x2af03b (0x7f89b50ea03b in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: torch::autograd::Variable::Impl::release_resources() + 0x17 (0x7f89b535cd27 in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #6: <unknown function> + 0x124cfb (0x7f89b6364cfb in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x3204af (0x7f89b65604af in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x3204f1 (0x7f89b65604f1 in /home/ubuntu/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #23: __libc_start_main + 0xf0 (0x7f89c2c3b830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by mmreza79** [comment]
@SungjinChoi1128 , It seems that your CuDNN has problem or corrupted, that's why it getting "CUDNN_STATUS_NOT_INITIALIZED" error. Make sure you have correctly installed CUDA and CuDNN versions. Furthermore, you can check if your installed PyTorch version is compatible with CUDA and CuDNN. For instance, I faced problem to run pix2pixHD architecture with PyTorch 0.4.0 but solved when upgraded to 0.4.1. However, my error was different. So, my suggestion to install latest PyTorch version and check CUDA and CuDNN. You may reinstall them.

**Comment by SungjinChoi1128** [comment]
@mmreza79 Thanks for the advice. I doubt if its a problem with CuDNN compatibility as I am able to train with the sample data set with 8 images. The error occurs only when I try to train with my own dataset. My data set has the same height and width and 8 images
My commend is: 
python train.py --name label2city_face --no_instance --batchSize 4 --gpu_ids 0,1,2,3 --label_nc 13 

Error messages
create web directory ./checkpoints/label2city_face/web...
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/SpatialReflectionPadding.cu
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __c
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77
    raise output
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __c
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/pix2pixHD-master/models/pix2pixHD_model.py", line 165, in forward
    fake_image = self.netG.forward(input_concat)
  File "/home/ubuntu/pix2pixHD-master/models/networks.py", line 213, in forward
    return self.model(input)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __c
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in f
    input = module(input)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __c
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forwa
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_INTERNAL_ERROR
terminate called after throwing an instance of 'at::Error'
  what():  CUDA error: invalid device pointer (CudaCachingDeleter at /opt/conda/conda-bld/pytorch_1535491974311/work/aten
frame #0: THStorage_free + 0x44 (0x7fbc3b241314 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/to
frame #1: THTensor_free + 0x2f (0x7fbc3b2e0a1f in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/tor
frame #2: at::CUDALongTensor::~CUDALongTensor() + 0x9 (0x7fbc17ee6769 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/pyth
frame #3: torch::autograd::Variable::Impl::~Impl() + 0x291 (0x7fbc3ce36791 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib
frame #4: torch::autograd::Variable::Impl::~Impl() + 0x9 (0x7fbc3ce36909 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/p
frame #5: <unknown function> + 0x770d09 (0x7fbc3ce4fd09 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-pac
frame #6: <unknown function> + 0x770db4 (0x7fbc3ce4fdb4 in /home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-pac
<omitting python frames>
frame #21: __libc_start_main + 0xf0 (0x7fbc53eff830 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

**Comment by chenwydj** [comment]
@SungjinChoi1128 I met the same "invalid device pointer" problem. How did you solve it? Thanks!

**Comment by mikirui** [comment]
For your own dataset, to set a proper '--label_nc' in options/base_options.py may help solve this problem.

**Comment by yining1023** [comment]
Hi @SungjinChoi1128, I had the same error. I fixed it making sure all the image sizes are divisible by 32(https://github.com/NVIDIA/pix2pixHD#training-with-your-own-dataset). I think you can also use `--resize_or_crop` option to resize the images.
