### ISSUE TITLE
OOM Cuda with V1000 and using 12GB scripts

### ISSUE THREAD

**Issue by dboshardy** [NVIDIA/pix2pixHD#300]
I'm trying to train on my own data (A->B translation) and am getting OOM errors.  I have a 16GB V100 running with:

* CUDA 11.4 
* pytorch 1.9.1
* torchvision 0.10.1.  

It very quickly runs out of memory when loading the data and network.  The error message comes after creating the checkbpoints/name/web directory.  I tried with the same options as the 12G scripts and keep getting OOM errors.

> RuntimeError: CUDA out of memory. Tried to allocate 512.00 MiB (GPU 0; 15.78 GiB total capacity; 13.68 GiB already allocated; 200.75 MiB free; 14.27 GiB reserved in total by PyTorch)

I'm using this command:

```
python train.py \
    --name={name} \
    --dataroot=datasets/{name} \
    --no_instance \
    --label_nc=0 \
    --batchSize=8 \
    --niter=50 \
    --niter_decay=50 \
    --niter_fix_global=10 \
    --resize_or_crop=none \
    --netG local \
    --ngf 32 \
    --num_D 3 \
    --fineSize=1024
```

The issue persists when using multiple V100s.

**Comment by zhangxiaojuan66** [comment]
你好，邮件已收到，祝你万事如意，生活愉快！

**Comment by dboshardy** [comment]
I believe I have solved this by setting the batch size to the number of GPUs.  I also downgraded to python 3.8 and pytorch 1.7.1 with the appropriate torchvision.
