### ISSUE TITLE
Can't use my own dataset for training

### ISSUE THREAD

**Issue by lzh19961031** [NVIDIA/pix2pixHD#51]
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    Variable(data['image']), Variable(data['feat']), infer=save_fake)
  File "/home/201683105/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/201683105/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/201683105/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/201683105/pix2pixHD/models/pix2pixHD_model.py", line 163, in forward
    fake_image = self.netG.forward(input_concat)
  File "/home/201683105/pix2pixHD/models/networks.py", line 213, in forward
    return self.model(input)             
  File "/home/201683105/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/201683105/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/201683105/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/201683105/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 36, 7, 7], expected input[1, 38, 582, 1030] to have 36 channels, but got 38 channels instead
terminate called after throwing an instance of 'at::Error'
  what():  CUDA error (59): device-side assert triggered (check_status at /opt/conda/conda-bld/pytorch_1532579805626/work/aten/src/ATen/cuda/detail/CUDAHooks.cpp:36)
frame #0: at::detail::CUDAStream_free(CUDAStreamInternals*&) + 0x50 (0x7f6d3a831c90 in /home/201683105/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2.so)
frame #1: THCStream_free + 0x13 (0x7f6d177f00a3 in /home/201683105/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0xc382cd (0x7f6d3cbaf2cd in /home/201683105/anaconda3/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #13: __libc_start_main + 0xf0 (0x7f6d50de0830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by tcwang0509** [comment]
What's the command you used to train? It seems the channel size of your input images does not follow your command.

**Comment by seanpguy** [comment]
For those interested, mine was a case of not specifying size:

**Comment by seanpguy** [comment]
For those interested, my issue was a case of not specifying size. This worked:

python train.py --name 01_gaudiInfill_512p --dataroot ./datasets/01_gaudiInfill/ --label_nc 0 --loadSize 512 --fineSize 512 --no_instance

**Comment by Avyukth** [comment]
> For those interested, my issue was a case of not specifying size. This worked:
> 
> python train.py --name 01_gaudiInfill_512p --dataroot ./datasets/01_gaudiInfill/ --label_nc 0 --loadSize 512 --fineSize 512 --no_instance

@seanpguy  can you train with only RGB Image?(no train_label and train_inst data)

**Comment by mmreza79** [comment]
Yes, You can.  In above command keep your "train_A" and "train_B" sub folders under "01_gaudiInfill" folder. It will train your model from A to B.

**Comment by mmreza79** [comment]
@hepinghu, since your input A is rgb and output B is binary map you should you "--input_nc 3 --output_nc 1". did you try with this? In data/aligned_dataset.py script, use ".convert('L') or .convert('1')" for loading B images.

**Comment by hepinghu** [comment]
I have only tried '-output_nc 1', and I will try again as you say, thanks.


来自 魅族 PRO 6s

-------- 原始邮件 --------
发件人：Mohammad Mohsin Reza <notifications@github.com>
时间：周五 11月30日 01:00
收件人：NVIDIA/pix2pixHD <pix2pixHD@noreply.github.com>
抄送：hepinghu <silencehehp@163.com>,Mention <mention@noreply.github.com>
主题：Re: [NVIDIA/pix2pixHD] Can't use my own dataset for training (#51)

**Comment by hepinghu** [comment]
> @hepinghu, since your input A is rgb and output B is binary map you should you "--input_nc 3 --output_nc 1". did you try with this? In data/aligned_dataset.py script, use ".convert('L') or .convert('1')" for loading B images.



> @hepinghu, since your input A is rgb and output B is binary map you should you "--input_nc 3 --output_nc 1". did you try with this? In data/aligned_dataset.py script, use ".convert('L') or .convert('1')" for loading B images.

I tried 'CUDA_VISIBLE_DEVICES=7 python train.py --name seg_512p --no_instance --label_nc 0 --fineSize 512 --dataroot './datasets/cancseg/' --output_nc 1 --input_nc 3',,,,and use " .convert('1')" for loading B images.  but it still don't work.    
The problem that arises is：
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    for i, data in enumerate(dataset, start=epoch_iter):
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hhp/project_github/pix2pixHD-master/data/aligned_dataset.py", line 62, in __getitem__
    B_tensor = transform_B(B)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 42, in __call__
    img = t(img)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 61, in __call__
    return F.to_tensor(pic)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/functional.py", line 71, in to_tensor
    img = img.view(pic.size[1], pic.size[0], nchannel)
RuntimeError: invalid argument 2: size '[1024 x 1024 x 1]' is invalid for input with 131072 elements at /pytorch/torch/lib/TH/THStorage.c:41。
Do you have any idea?

**Comment by hepinghu** [comment]
I tried 'python train.py --name seg_512p --no_instance --label_nc 0 --fineSize 512 --dataroot './datasets/cancseg/' --output_nc 1 --input_nc 3',,,,and use " .convert('1')" for loading B images.  but it still don't work.    
The problem that arises is：
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    for i, data in enumerate(dataset, start=epoch_iter):
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/hhp/project_github/pix2pixHD-master/data/aligned_dataset.py", line 62, in __getitem__
    B_tensor = transform_B(B)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 42, in __call__
    img = t(img)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 61, in __call__
    return F.to_tensor(pic)
  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/functional.py", line 71, in to_tensor
    img = img.view(pic.size[1], pic.size[0], nchannel)
RuntimeError: invalid argument 2: size '[1024 x 1024 x 1]' is invalid for input with 131072 elements at /pytorch/torch/lib/TH/THStorage.c:41。
Do you have any idea?




At 2018-11-30 01:00:25, "Mohammad Mohsin Reza" <notifications@github.com> wrote:


@hepinghu, since your input A is rgb and output B is binary map you should you "--input_nc 3 --output_nc 1". did you try with this? In data/aligned_dataset.py script, use ".convert('L') or .convert('1')" for loading B images.

**Comment by hepinghu** [comment]
I tried 'CUDA_VISIBLE_DEVICES=7 python train.py --name seg_512p --no_instance --label_nc 0 --fineSize 512 --dataroot './datasets/cancseg/' --output_nc 1 --input_nc 3',,,,and use " .convert('1')" for loading B images.  but it still don't work.   
 The problem that arises is：

Traceback (most recent call last):  File "train.py", line 51, in <module>    for i, data in enumerate(dataset, start=epoch_iter):  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__    return self._process_next_batch(batch)  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch    raise batch.exc_type(batch.exc_msg)RuntimeError: Traceback (most recent call last):  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop    samples = collate_fn([dataset[i] for i in batch_indices])  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>    samples = collate_fn([dataset[i] for i in batch_indices])  File "/home/hhp/project_github/pix2pixHD-master/data/aligned_dataset.py", line 62, in __getitem__    B_tensor = transform_B(B)  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 42, in __call__    img = t(img)  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/transforms.py", line 61, in __call__    return F.to_tensor(pic)  File "/usr/share/Anaconda3/lib/python3.6/site-packages/torchvision-0.2.0-py3.6.egg/torchvision/transforms/functional.py", line 71, in to_tensor    img = img.view(pic.size[1], pic.size[0], nchannel)RuntimeError: invalid argument 2: size '[1024 x 1024 x 1]' is invalid for input with 131072 elements at /pytorch/torch/lib/TH/THStorage.c:41。Do you have any idea?


来自 魅族 PRO 6s

-------- 原始邮件 --------
发件人：silencehehp <silencehehp@163.com>
时间：周五 11月30日 08:17
收件人：NVIDIA/pix2pixHD <reply@reply.github.com>
主题：Re: [NVIDIA/pix2pixHD] Can't use my own dataset for training (#51)

**Comment by mmreza79** [comment]
Did you tried with ".convert('L')" to load B image? Use "--loadSize 512" as same size as fineSize for fine tune. You may chage it later.

**Comment by hepinghu** [comment]
It still don't work....


来自 魅族 PRO 6s

-------- 原始邮件 --------
发件人：Mohammad Mohsin Reza <notifications@github.com>
时间：周五 11月30日 17:19
收件人：NVIDIA/pix2pixHD <pix2pixHD@noreply.github.com>
抄送：hepinghu <silencehehp@163.com>,Mention <mention@noreply.github.com>
主题：Re: [NVIDIA/pix2pixHD] Can't use my own dataset for training (#51)

**Comment by mmreza79** [comment]
It should work. By the way, which pyTorch and torchvision version you are using? I remember I got such kind of error long back ago but forgot how to solve. One thing I remember solve a problem by changing Torch version. You can also check. I am using Torch 0.4.1 and torchvision 0.2.1.

**Comment by ygqhfut** [comment]
@mmreza79 Hello, we used the train_A to train_B method and found that the training process works well. But the final test is very bad. Why is this?
Our training command is as follows:
python train.py --name label2city_512p --label_nc 0 --no_instance
testing comands:
python test.py --name label2city_512p --netG local --ngf 32 --resize_or_crop none --no_instance

**Comment by mmreza79** [comment]
Please have a look scripts folder where you will find training and corresponding testing commends. In your training commend use are using --netG global (by default) and --ngf 64 (by default) but in testing commend you are using --netG local and --ngf 32. Remove this 2 param from test commend which by default will take --netG global and --ngf 64. --netG local param only have to use in training and testing if you train your model further for local enhencer to enlarge image resolution.

**Comment by ygqhfut** [comment]
> Please have a look scripts folder in git repo where you will find training and corresponding testing commends. In your training commend, you are using --netG global (by default) and --ngf 64 (by default) but in testing commend you are using --netG local and --ngf 32. Remove this 2 param from test commend which by default will take --netG global and --ngf 64 and also add --label_nc 0 cause you trained model with this param. --netG local param only have to use in training and testing if you train your model further for local enhencer to enlarge image resolution.

Thanks for your advice! It works well. Thank you very much again!

**Comment by mmreza79** [comment]
@ygqhfut, you are most welcome.

**Comment by LJ2lijia** [comment]
@mmreza79 Hello, we used the train_A to train_B method.  And the size of origin image is 200*200, the number of the training set is 2100. The Graphics memory is 11G. But it doesn't work. The problem that arises is：RuntimeError: CUDA error: out of memory.
Our training command is as follows:
python train.py --name label2city_512p --label_nc 0 --no_instance

**Comment by mmreza79** [comment]
Hello @LJ2lijia , Are you sure that there are enough free GPU memory? If at least 6/7GB free or whole GPU free then that is not out of memory issue. One more thing, your image size is 200x200 which may create the problem. Please check with resize image to 256x256. This model take image size which is divisible by 32.

**Comment by LJ2lijia** [comment]
@mmreza79 Thank for your advice. We changed the command to python train.py --name label2city_512p  --label_nc 0 --no_instance  --ngf 32. And it works. But we don't know the reason.

**Comment by mmreza79** [comment]
The generator network takes filter size 64 or 32. That's why it requires any image size divisible by 32. If you you --ngf 32 means first layer of generator network takes filter size 32. If you have enough gpu memory better to use 64, but remember that image size should divisible by 32.

**Comment by ygqhfut** [comment]
@mmreza79  Hello, I want to know how the local features of the local generator are guaranteed. I am a bit confused now.
